#!/bin/bash

set -xe

rm -rf /opt/qt6/*
rm -rf /home/afiestas/Projects/qt6

cd /home/afiestas/Projects/
git clone git://code.qt.io/qt/qt5.git --branch 6.8 qt6
cd qt6
./init-repository

mkdir build
cd build/
cmake ../ -DCMAKE_INSTALL_PREFIX=/opt/qt6 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DFEATURE_journald=ON DFEATURE_libproxy=ON -DFEATURE_openssl_linked=ON -DFEATURE_system_sqlite=ON -DFEATURE_system_xcb_xinput=ON -DFEATURE_no_direct_extern_access=ON -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_MESSAGE_LOG_LEVEL=STATUS -DQT_FEATURE_webengine_system_ffmpeg=ON -DQT_FEATURE_webengine_system_icu=ON -DQT_FEATURE_webengine_system_libevent=ON -DQT_FEATURE_webengine_proprietary_codecs=ON -DQT_FEATURE_webengine_kerberos=ON -DQT_FEATURE_webengine_webrtc_pipewire=ON -GNinja

ninja install
